version: '2'

services:
  nginx:
    container_name: nginx-container
    build: ./docker-build/nginx
    ports:
      - "80:80"
    links:
      - php
  php:
    container_name: php-container
    build: ./docker-build/php
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: name_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

